-- ============================================================
-- KTP Interflex – Woningbeheer: CODES & WIFI
-- Tabel woning_codes + trigger + beveiligde functies voor de pagina "🔑 Codes".
-- Dit is een kopie van wat in Supabase staat (stand 07-10-2026), zodat het
-- opnieuw op te bouwen is. Voer uit in Supabase > SQL Editor > New Query.
--
-- Beveiliging: de tabel is NIET direct bereikbaar met de publieke (anon) sleutel.
-- Lezen en wijzigen kan alleen via de functies hieronder, met een geldig
-- sessietoken (zelfde controle als bij de pincodes: _sessie_gebruiker).
--   - lezen:     iedere ingelogde gebruiker
--   - wijzigen:  alleen rol huismeester of backoffice (echte rol, niet "Bekijk als")
-- ============================================================

-- 1. TABEL
CREATE TABLE IF NOT EXISTS woning_codes (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  woning_id        integer NOT NULL REFERENCES woningen(id) ON DELETE CASCADE,
  type             text NOT NULL DEFAULT 'wifi' CHECK (type IN ('wifi','sleutelkluis','alarm','overig')),
  omschrijving     text NOT NULL DEFAULT '',
  code             text NOT NULL DEFAULT '',
  opmerking        text,
  aangemaakt_op    timestamptz NOT NULL DEFAULT now(),
  aangemaakt_door  text,
  gewijzigd_op     timestamptz NOT NULL DEFAULT now(),
  gewijzigd_door   text
);

-- 2. TRIGGER: "gewijzigd op" alleen bijwerken als er inhoudelijk iets verandert
CREATE OR REPLACE FUNCTION public.woning_codes_set_gewijzigd()
 RETURNS trigger LANGUAGE plpgsql SET search_path TO 'public'
AS $$
begin
  if (new.code, new.omschrijving, new.type, coalesce(new.opmerking,'')) is distinct from (old.code, old.omschrijving, old.type, coalesce(old.opmerking,'')) then
    new.gewijzigd_op := now();
  else
    new.gewijzigd_op := old.gewijzigd_op;
    new.gewijzigd_door := old.gewijzigd_door;
  end if;
  return new;
end $$;

DROP TRIGGER IF EXISTS woning_codes_gewijzigd ON public.woning_codes;
CREATE TRIGGER woning_codes_gewijzigd BEFORE UPDATE ON public.woning_codes
  FOR EACH ROW EXECUTE FUNCTION woning_codes_set_gewijzigd();

-- 3. FUNCTIES (security definer: draaien met rechten van de eigenaar, controleren zelf de sessie)

-- Alle codes ophalen — iedere ingelogde gebruiker
CREATE OR REPLACE FUNCTION public.app_codes_lijst(p_token uuid)
 RETURNS json LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $$
declare g public.gebruikers;
begin
  g := public._sessie_gebruiker(p_token);
  if g.id is null then return json_build_object('ok', false, 'fout', 'Sessie verlopen, log opnieuw in'); end if;
  return json_build_object('ok', true, 'codes', coalesce((
    select json_agg(c order by c.type, c.omschrijving) from public.woning_codes c), '[]'::json));
end $$;

-- Toevoegen (p_id null) of wijzigen — alleen huismeester / backoffice
CREATE OR REPLACE FUNCTION public.app_code_opslaan(p_token uuid, p_id bigint, p_woning_id integer,
  p_type text, p_omschrijving text, p_code text, p_opmerking text)
 RETURNS json LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $$
declare g public.gebruikers; nieuw_id bigint;
begin
  g := public._sessie_gebruiker(p_token);
  if g.id is null then return json_build_object('ok', false, 'fout', 'Sessie verlopen, log opnieuw in'); end if;
  if g.rol not in ('huismeester','backoffice') then
    return json_build_object('ok', false, 'fout', 'Alleen huismeester en backoffice kunnen codes wijzigen');
  end if;
  if coalesce(trim(p_code),'') = '' or coalesce(trim(p_omschrijving),'') = '' then
    return json_build_object('ok', false, 'fout', 'Omschrijving en code zijn verplicht');
  end if;
  if p_id is null then
    insert into public.woning_codes (woning_id, type, omschrijving, code, opmerking, aangemaakt_door, gewijzigd_door)
    values (p_woning_id, p_type, trim(p_omschrijving), trim(p_code), nullif(trim(coalesce(p_opmerking,'')),''), g.naam, g.naam)
    returning id into nieuw_id;
  else
    update public.woning_codes
       set type = p_type, omschrijving = trim(p_omschrijving), code = trim(p_code),
           opmerking = nullif(trim(coalesce(p_opmerking,'')),''), gewijzigd_door = g.naam
     where id = p_id
    returning id into nieuw_id;
    if nieuw_id is null then return json_build_object('ok', false, 'fout', 'Code niet gevonden'); end if;
  end if;
  return json_build_object('ok', true, 'id', nieuw_id);
end $$;

-- Verwijderen — alleen huismeester / backoffice
CREATE OR REPLACE FUNCTION public.app_code_verwijderen(p_token uuid, p_id bigint)
 RETURNS json LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $$
declare g public.gebruikers;
begin
  g := public._sessie_gebruiker(p_token);
  if g.id is null then return json_build_object('ok', false, 'fout', 'Sessie verlopen, log opnieuw in'); end if;
  if g.rol not in ('huismeester','backoffice') then
    return json_build_object('ok', false, 'fout', 'Alleen huismeester en backoffice kunnen codes verwijderen');
  end if;
  delete from public.woning_codes where id = p_id;
  return json_build_object('ok', true);
end $$;

REVOKE ALL ON FUNCTION public.app_codes_lijst(uuid) FROM public;
REVOKE ALL ON FUNCTION public.app_code_opslaan(uuid, bigint, integer, text, text, text, text) FROM public;
REVOKE ALL ON FUNCTION public.app_code_verwijderen(uuid, bigint) FROM public;
GRANT EXECUTE ON FUNCTION public.app_codes_lijst(uuid) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.app_code_opslaan(uuid, bigint, integer, text, text, text, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.app_code_verwijderen(uuid, bigint) TO anon, authenticated;

-- 4. TABEL DICHTZETTEN (pas uitvoeren als de app de functies hierboven gebruikt)
ALTER TABLE public.woning_codes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS allow_all_woning_codes ON public.woning_codes;
REVOKE ALL ON public.woning_codes FROM anon, authenticated;
